//Gestió d'errors amb async/await: Modifica la funció de l'exercici 4 per a que capturi qualsevol 
//possible error utilitzant un bloc try/catch.

